### PR TITLE
Fix #646 - Fix calculation hit ratio in StandardCache's cache report.

### LINKED ISSUE #646: In StandardCacheManager cache report, Hit ratio is always 0.00 if not hit all...
#### Version
3.0.8.RELEASE

#### Problem
At `StandardCacheManager` cache report, there is a problem that the hit ratio and miss ratio are not calculated correctly.

```console
[THYMELEAF][*][*][*][CACHE_REPORT]        2 elements |            2 puts |            8 gets |            6 hits |            2 misses | 0.00 hit ratio | 1.00 miss ratio - [TEMPLATE_CACHE]
```
* hit ratio is always `0.00` if not hit all.
* miss ratio is always `1.00`.

#### Cause
At [StandardCache.java#L334-L340](https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-3.0.8.RELEASE/src/main/java/org/thymeleaf/cache/StandardCache.java#L334-L340)

```java
long hitCount = getHitCount();
long missCount = getMissCount();
long putCount = getPutCount();
long getCount = getGetCount();

double hitRatio = hitCount / getCount; // calculation mistake...
double missRatio = 1 - hitRatio;
```
The division result of long is stored in double...

#### Solution

```java
double hitRatio = (double) hitCount / (double) getCount;
```

Please consider it.

### PR DESCRIPTION
**Pull request by yoshikawaa**
#646 fixed.

Please check it, Thanks.

### CODE REVIEW

**Review by danielfernandez — APPROVED** [review]

**Comment by danielfernandez** [comment]
Thanks a lot @yoshikawaa!

**Comment by yoshikawaa** [comment]
@danielfernandez 
Thank you for accepting.

File: src/main/java/org/thymeleaf/cache/StandardCache.java [hunk 1]
```diff
@@ -336,7 +336,7 @@ private void outputReportIfNeeded() {
                     long putCount = getPutCount();
                     long getCount = getGetCount();
 
-                    double hitRatio = hitCount / getCount;
+                    double hitRatio = (double) hitCount / (double) getCount;
```
Comment (php-coder) [inline src/main/java/org/thymeleaf/cache/StandardCache.java:339]: @yoshikawaa @danielfernandez Why not use `getHitRatio()` method to reduce duplication? This also adds a protection against division by zero.

File: src/main/java/org/thymeleaf/cache/StandardCache.java [hunk 2]
```diff
@@ -336,7 +336,7 @@ private void outputReportIfNeeded() {
...
                     double missRatio = 1 - hitRatio;
```
Comment (php-coder) [inline src/main/java/org/thymeleaf/cache/StandardCache.java:340]: > double missRatio = 1 - hitRatio;

BTW this can be replaced by using `getMissRatio()` method.
